#!/usr/local/bin/node

var fs = require('fs');
var exec = require('child_process').exec;
var colors = require('colors');
var ejs = require('ejs');

// add methods to the console for each of the styles in the colors library
// e.g. console.green('hello', 'world')
for (var style in colors.styles) {
  console[style] = function(color) {
    var args = [].slice.call(arguments, 1);
    var styledStrings = args.map(str => JSON.stringify(str)[color]);
    console.log.apply(this, styledStrings);
  }.bind(console, style);
}

/* all color options:
 * black, red, green, yellow, blue, magenta, cyan, white, gray, grey
 * bgBlack, bgRed, bgGreen, bgYellow, bgBlue, bgMagenta, bgCyan, bgWhite
 * reset, bold, dim, italic, underline, inverse, hidden, strikethrough
 */


// method to convert to pascal-case
String.prototype.pascal = function() {
  return this.replace(/^([a-z])/, let => let.toUpperCase())
             .replace(/[\-\_]([a-zA-Z])/,  let => let[1].toUpperCase());
}


var commands = { help, init, seed };

function help() {
  console.yellow('Welcome to mongoose-model-cli!');
},

function init() {
  var dir = fs.readdirSync('./');
  var modelDir = dir.indexOf('models');
  if (modelDir !== -1) return;
  fs.mkdirSync('./models');
  fs.mkdirSync('./models/seed');
  fs.mkdirSync('./models/migrations');
  fs.createReadStream('templates/.connection-string.js').pipe(fs.createWriteStream('models/.connection-string.js'));
  fs.createReadStream('templates/seedfile.js').pipe(fs.createWriteStream('models/seed/seedfile.js'));
},

function seed() {
  exec('node ./models/seed/seedfile.js', function(err, stdout, stderr) {
    if (err) console.error(err);
    else console.log(stdout);
  });
},


commands.create = commands.generate = commands.g = { model, migration };

function model() {
  var name = process.argv[4];
  if (!name) return console.bgRed('Must supply a name for the model.');
  name = name.pascal();
  var attrs = process.argv.slice(5);
  attrs = attrs.reduce((obj, pair) => {
    pair = pair.split(':');
    obj[pair[0]] = pair[1].pascal();
    return obj;
  }, {});

  for (var attr in attrs) {
    var dataType = attrs[attr];
    if (dataType.slice(0, 2) === 'Id') {
      attrs[attr] = `Schema.Types.ObjectId, ref: '${dataType.slice(2)}'`;
    } 
    else if (dataType === 'Mixed') {
      attrs[attr] = `Schema.Types.Mixed`;
    }
    else if (!global[dataType]) {
      return console.bgRed('Invalid data type ' + dataType);
    }
  }

  commands.init();
  console.cyan(`Creating new model: ${name}`);

  var file = ejs.render(fs.readFileSync('./templates/model.ejs').toString(), { name, attrs });

  fs.writeFile(`models/${name}.js`, file, err => {
    if (err) console.red(err);
    else console.green(name + ' was successfully created!');
  });
},


function migration() {
  var name = process.argv[4];
  if (!name) return console.red('You must specify the model for this migration');
  name = name.pascal();
  var models = fs.readdirSync('./models');
  var modelInd = models.indexOf(name + '.js');
  if (modelInd === -1) 
    return console.red('You have yet to create a model: ' + name);

  console.cyan('Creating a migration file for: ' + name);
  var file = ejs.render(fs.readFileSync('./templates/migration.ejs').toString(), { name });

  fs.writeFile(`models/migrations/${name}-${Date.now()}.js`, file, err => {
    if (err) console.red(err);
    else console.green(`Migration for ${name} was successfully created!`);
  });
}


var command = process.argv[2];
var type = process.argv[3];

try {
  if (type)
    commands[command][type]();
  else
    commands[command]();
} catch(err) {
  if (Object.keys(err).length) console.bgRed(err);
  commands.help();
}